---
- name: Ensure config directory exists
  file:
    path: /etc/cloudwatch_exporter
    state: directory
    owner: prometheus
    group: prometheus

- name: Download CloudWatch Exporter (Java Jar)
  get_url:
    url: "https://repo1.maven.org/maven2/io/prometheus/cloudwatch_exporter/0.16.0/cloudwatch_exporter-0.16.0-jar-with-dependencies.jar"
    dest: "/usr/local/bin/cloudwatch_exporter.jar"
    owner: prometheus
    group: prometheus
    mode: "0644"

- name: Deploy CloudWatch Config
  template:
    src: cloudwatch_config.yml.j2
    dest: /etc/cloudwatch_exporter/config.yml
    owner: prometheus
    group: prometheus

- name: Install systemd service
  template:
    src: cloudwatch_exporter.service.j2
    dest: /etc/systemd/system/cloudwatch_exporter.service
  notify: Restart CloudWatch Exporter

- name: Create Prometheus Target File
  copy:
    dest: "/etc/prometheus/file_sd/cloudwatch_exporter.json"
    content: |
      [
        {
          "targets": ["localhost:9106"],
          "labels": { "job": "cloudwatch_exporter" }
        }
      ]
