---
- name: Gather S3 Bucket Information
  amazon.aws.s3_bucket_info:
    region: "{{ aws_region | default('us-east-1') }}"
    bucket_tagging: true
  register: all_buckets

- name: Consolidate and Filter Buckets with Tags
  set_fact:
    filtered_buckets: >-
      {{ 
        all_buckets.buckets 
        | selectattr('tags.project', 'defined') 
        | selectattr('tags.project', 'equalto', 'monitoring-system') 
        | list 
      }}

- name: DEBUG - SHOW ME THE MATCHING BUCKETS
  debug:
    msg: "Final list for Prometheus: {{ filtered_buckets | map(attribute='name') |
      list }}"

- name: Generate File SD JSON for Custom Exporters
  template:
    src: aws_resources.json.j2
    dest: /etc/prometheus/file_sd/aws_resources.json
    owner: prometheus
    group: prometheus
    mode: "0644"

- name: Force Prometheus to refresh targets
  systemd:
    name: prometheus
    state: restarted
