---
- name: "Load vars for {{ item | basename }}"
  include_vars:
    file: "{{ item }}"
    name: "current_exporter"

- name: "Template Systemd Service"
  template:
    src: exporter.service.j2 # Ansible looks in ../templates/ automatically
    dest: "/etc/systemd/system/{{ item | basename | replace('.yml', '') }}.service"
  register: service_update

- name: "Template Prometheus Target"
  template:
    src: target.json.j2
    dest: "/etc/prometheus/file_sd/{{ item | basename | replace('.yml', '') }}.json"

- name: "Restart service if changed"
  systemd:
    name: "{{ item | basename | replace('.yml', '') }}"
    state: restarted
    enabled: yes
    daemon_reload: yes
  when: service_update.changed