---
- name: "Install Node Exporter on Remote Managed Nodes"
  # Target instances tagged with 'Monitoring: enabled'
  hosts: "tag_Monitoring-Stack_prometheus"
  become: true
  roles:
    - node_exporter_remote
