name: "Workflow 2: Ansible Provisioning"

on:
    workflow_dispatch:
    #push:
    #branches: [main]
    #paths:
    #- "ansible/**"

permissions:
    id-token: write # Required for OIDC
    contents: read # Required for checkout

jobs:
    ansible-dry-run:
        name: "Ansible Check (Dry Run)"
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Configure AWS Credentials (OIDC)
              uses: aws-actions/configure-aws-credentials@v4
              with:
                  role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
                  aws-region: us-east-1

            - name: Set up SSH agent
              uses: webfactory/ssh-agent@v0.9.0
              with:
                  ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.11"
                  cache: "pip"

            - name: Install Dependencies
              run: |
                  pip install ansible boto3 botocore
                  ansible-galaxy collection install community.aws

            - name: Run Playbook (Check Mode)
              run: |
                  # We use -i to point to our dynamic inventory logic later
                  ansible-playbook -i ansible/inventory.aws_ec2.yml ansible/site.yml --check --diff
              env:
                  ANSIBLE_HOST_KEY_CHECKING: "False"
                  AWS_REGION: us-east-1

    ansible-apply:
        name: "Ansible Apply (Provisioning)"
        needs: ansible-dry-run
        runs-on: ubuntu-latest
        environment: test # Your manual approval gate
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Configure AWS Credentials (OIDC)
              uses: aws-actions/configure-aws-credentials@v4
              with:
                  role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
                  aws-region: us-east-1

            - name: Set up SSH agent
              uses: webfactory/ssh-agent@v0.9.0
              with:
                  ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.11"

            - name: Install Dependencies
              run: |
                  pip install ansible boto3 botocore
                  ansible-galaxy collection install community.aws

            - name: Run Master Playbook
              run: |
                  ansible-playbook -i ansible/inventory/ ansible/site.yml
              env:
                  ANSIBLE_HOST_KEY_CHECKING: "False"
                  AWS_REGION: us-east-1
