name: Single-Region Terraform Deployment

on:
  workflow_dispatch:
  # push:
  #   branches: [ main ]
  #   paths:
  #  - 'terraform/*.tf'         # Changes to main.tf, providers, etc.
  #  - 'terraform/modules/**'   # Changes to any reusable module

permissions:
  contents: read
  id-token: write

env:
  AWS_REGION: us-east-1

jobs:
  # --- JOB 1: PLAN ---
  terraform_plan:
    name: "Terraform Plan"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.12.1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init
        run: terraform init -reconfigure
        working-directory: ./terraform

      - name: Terraform Plan
        run: terraform plan -input=false -out=tfplan
        working-directory: ./terraform

      - name: Upload Plan Artifact
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: terraform/tfplan

  # --- JOB 2: APPLY ---
  terraform_apply:
    name: "Terraform Apply"
    needs: terraform_plan
    runs-on: ubuntu-latest
    environment: test # Requires manual approval in GitHub Settings, change to test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-region: ${{ env.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Download Plan Artifact
        uses: actions/download-artifact@v4
        with:
          name: tfplan
          path: terraform/

      - name: Terraform Init
        run: terraform init -reconfigure
        working-directory: ./terraform

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
        working-directory: ./terraform
